---
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
      - gem: 'net-ip'
  required:
    ':system_tests':
      - gem: beaker
        version: '~> 4.0'
        from_env: BEAKER_VERSION
      - gem: beaker-pe
      - gem: beaker-docker
      - gem: beaker-puppet
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper
      - gem: serverspec
    ':release':
      - gem: github_changelog_generator
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.0')"
        git: 'https://github.com/skywinder/github-changelog-generator'
      - gem: puppet-blacksmith
      - gem: voxpupuli-release      
        git: 'https://github.com/voxpupuli/voxpupuli-release-gem'
      - gem: puppet-strings
        version: '>= 1.0'
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.travis.yml:
  ruby_versions:
    - 2.4.4
  docker_sets:
    - set: ubuntu1804-64
    - set: ubuntu1604-64
    - set: centos7-64
    - set: debian9-64
    - set: debian8-64
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
  notifications:
    irc:
      on_success: always
      on_failure: always
      channels:
        - "chat.freenode.org#voxpupuli-notifications"
  secure: '0EBUR60jTMljMKtTZCKOLBdYTNqpeVazUXwJ9HcYJq0hR4k3bIVAO79Q5It78Qycqhren/XBM48+tEcUOcBV6eFcqLBGHO94TIoYLk6g+QmMpfI8Bzp8oFteLMs3HAE6H0j+BDamc8ppfTjxBUq1bxG9Axlw3rafxeOrF+CJnOXB1tyOvyv7/EOsF52d4yWDRqg0PlmzSFXAzdt7RN/7Jb/9HCHP73GPJwx+fEav9KTkcCWJsKhe3vYrXlNPjqJb4T1lm10W7TE0PRricgasjsg0P0KMAjvwWpXbAySWxx171HC6V0nZY9ORp8Pgvx67idX+XxUXTA/X0rf8IW1GXDF0O+VOfbPrxQRgFG+B/wZhVosOyfJnPlYlfDODQI7GgbGFNf5mh8qno9KqAHBDyd0uzTum1QY+NpOvEMN2wHv4BNTmwgpkLtdsWBrEVu71WS8XMiAjaNkNf85F3K9A7uuefG4LckqhHe3yAlPQ9mPv2CaAw3XKQdwJxULQJlwtFZmTBWPaRyPyHr0v3Uq0PCvXfKwvy1OQlvwq2RUInCPMbN7aroTv6ywBjg+F6+R0kirApXSyiqNrdcw+nVr+sDopDCKLp12WRzE5yIwO7Gzvw6w4dbhaSRKag6jJdNTjJRZtDtVc2CkmYY7TDtMxI0miTyLTLR7gXjM9Z6Z4690='
spec/spec_helper.rb:
  mock_with: ':rspec'
